### ISSUE TITLE
Violation of GPL

### ISSUE THREAD

**Issue by mgisbers** [lupael/routeros-scripts#1]
This projects forks an exitisting project and tries to remove references to the original project. Doing so violates the projects license (GPL).

You have to revert changes not extending or fixing the the original code and reinstate origins copyright and contribution statements.

**Comment by lupael** [comment]
Read twice 
![image](https://user-images.githubusercontent.com/43011721/150575409-e99a72a4-7b39-4502-8e7b-bd0b4dc1d2ec.png)
There is no Author mentioned 
![image](https://user-images.githubusercontent.com/43011721/150575704-3019b8d8-67e6-4ca0-8c85-762bd04c0943.png)

and
![image](https://user-images.githubusercontent.com/43011721/150575890-80ba328e-3cb9-4034-ad9b-7ac6bd0090e9.png)
